OFS-112: Fixed Contribution Plan form and Contribution Plan picker
openimis/openimis-fe-contribution_plan_js pull request #20
Opened 2021-03-04 15:31 UTC by dborowiecki

TICKET: [OFS-112](https://openimis.atlassian.net/browse/OFS-112)

2021-03-04 16:23 UTC, rstencel commented
> This pull request **introduces 2 alerts** when merging [b50b587](https://github.com/openimis/openimis-fe-contribution_plan_js/commit/b50b58752f4cad8508ccb11b6c45131bd80257b3) into [830ffd6](https://github.com/openimis/openimis-fe-contribution_plan_js/commit/830ffd6e291690b0f39493ad367f17a0b96f105b) - [view on LGTM.com](https://lgtm.com/projects/g/openimis/openimis-fe-contribution_plan_js/rev/pr-3ea88ce5784557930df797c689454653595ee682)
> 
> **new alerts:**
> 
>     * 2 for Unused variable, import, function or class

@dborowiecki please remove `decodeId` imports

2021-03-04 16:26 UTC, rstencel requested changes
> This pull request **introduces 2 alerts** when merging [b50b587](https://github.com/openimis/openimis-fe-contribution_plan_js/commit/b50b58752f4cad8508ccb11b6c45131bd80257b3) into [830ffd6](https://github.com/openimis/openimis-fe-contribution_plan_js/commit/830ffd6e291690b0f39493ad367f17a0b96f105b) - [view on LGTM.com](https://lgtm.com/projects/g/openimis/openimis-fe-contribution_plan_js/rev/pr-3ea88ce5784557930df797c689454653595ee682)
> 
> **new alerts:**
> 
>     * 2 for Unused variable, import, function or class

@dborowiecki please remove `decodeId` imports. The rest looks good to me.

2021-03-05 08:00 UTC, rstencel approved these changes

2021-03-05 12:33 UTC, delcroip approved these changes

2021-03-05 12:33 UTC, merged