OP-1916: Changed Projection for CPB fetch
openimis/openimis-fe-contribution_plan_js pull request #89
Opened 2024-10-04 09:05 UTC by dborowiecki

TICKET: [OP-1916](https://openimis.atlassian.net/browse/OP-1916)

2024-10-07 08:25 UTC, delcroip requested changes

2024-10-07 08:25 UTC, delcroip commented on src/components/ContributionPlanBundleContributionPlans.js
> +    decodeId,
core already imported above

2024-10-10 08:34 UTC, dragos-dobre commented
@dborowiecki Please combine the two fe-core imports.

2024-10-15 06:57 UTC, delcroip approved these changes

2024-10-15 06:57 UTC, merged